services:
  goldeneye-beef:
    image: 278521702583.dkr.ecr.us-west-2.amazonaws.com/arch/node-v20-builder:v2.0.2
    working_dir: /app/components/$MODULE
    volumes:
      - $HOME/.npmrc:/root/.npmrc
      - $PROJECT_ROOT:/app
    env_file:
      - $PROJECT_ROOT/components/$MODULE/.env.playpen
    ports:
      - "3000:3000"
