version: '3'

services:

  docs:
    image: 278521702583.dkr.ecr.us-west-2.amazonaws.com/arch/node-v20-chrome:v1.0.2
    working_dir: /app/frontends/$MODULE
    volumes:
      - $HOME/.npmrc:/root/.npmrc
      - $PROJECT_ROOT:/app
    environment:
      - BUILDKITE=1
      - MODULE=$MODULE
